#!/usr/bin/env python
import sys
import subprocess

def usage():
    ''' Print usage and exit'''
    print('Usage: ' + sys.argv[0] + ' server(s)')
    sys.exit()

def main():
    # Just assume everything after argv[0] is servers to connect to
    args=sys.argv[1:]

    # Decide number of rows and columns in the iTerm2 window
    if len(args) % 2 == 0:
        # Even
        rows=len(args)/2
        columns=len(args)/2
        even=1
    else:
        # Odd
        rows=len(args)/2+1
        columns=len(args)/2+1
        even=0

    # Print usage if there's no arguments
    if len(args) == 0:
        usage()

    # Start compiling the applescript
    ascript = '''tell application "iTerm2"
  tell current window
    create window with default profile
  end tell
  set p1 to (current session of current window)
'''

    index=1

    for i in range(1, rows):
        ascript += '''
  tell p{}
    set p{} to (split horizontally with same profile)
  end tell
    '''.format(index, index+1)
        index+=1

    for i in range(1, columns+even):
        ascript += '''
  tell p{}
    set p{} to (split vertically with same profile)
  end tell
    '''.format(i, i+columns)

    for i in range(0, len(args)):
        ascript += '''
  tell p{}
    write text "unset HISTFILE && ssh {}"
  end tell
    '''.format(i+1,args[i])

    ascript += '''
end tell'''

    # Execute applescript
    subprocess.call(['osascript', '-e', ascript])

if __name__ == '__main__':
    main()

